import type { VSCodeTheme } from "@/types/theme";

export type EditorType = "vscode" | "zed" | "cursor" | "neovim" | "helix";

export interface ExportFormat {
  content: string;
  filename: string;
  extension: string;
}

// Convert VSCode theme to Zed format
export function convertToZed(theme: VSCodeTheme): ExportFormat {
  const zedTheme = {
    $schema: "https://zed.dev/schema/themes/v0.2.0.json",
    name: theme.name,
    author: "Theme Editor",
    themes: [
      {
        name: theme.name,
        appearance: theme.type,
        style: {
          background: theme.colors["editor.background"] || "#1e1e1e",
          foreground: theme.colors["editor.foreground"] || "#d4d4d4",
          accent: theme.colors.focusBorder || "#007acc",
          border: theme.colors["panel.border"] || "#3e3e3e",
          "border.variant": theme.colors["editorGroup.border"] || "#444444",
          "editor.background": theme.colors["editor.background"] || "#1e1e1e",
          "editor.foreground": theme.colors["editor.foreground"] || "#d4d4d4",
          "editor.gutter.background":
            theme.colors["editorGutter.background"] || "#1e1e1e",
          "editor.line.number":
            theme.colors["editorLineNumber.foreground"] || "#858585",
          "editor.active_line.number":
            theme.colors["editorLineNumber.activeForeground"] || "#c6c6c6",
          "element.background": theme.colors["button.background"] || "#0e639c",
          text: theme.colors.foreground || "#cccccc",
          syntax: {
            keyword:
              theme.tokenColors.find((t) => t.scope.includes("keyword"))
                ?.settings.foreground || "#569cd6",
            string:
              theme.tokenColors.find((t) => t.scope.includes("string"))
                ?.settings.foreground || "#ce9178",
            comment:
              theme.tokenColors.find((t) => t.scope.includes("comment"))
                ?.settings.foreground || "#6a9955",
            function:
              theme.tokenColors.find((t) =>
                t.scope.includes("entity.name.function"),
              )?.settings.foreground || "#dcdcaa",
            variable:
              theme.tokenColors.find((t) => t.scope.includes("variable"))
                ?.settings.foreground || "#9cdcfe",
            number:
              theme.tokenColors.find((t) =>
                t.scope.includes("constant.numeric"),
              )?.settings.foreground || "#b5cea8",
            type:
              theme.tokenColors.find((t) =>
                t.scope.includes("entity.name.type"),
              )?.settings.foreground || "#4ec9b0",
          },
        },
      },
    ],
  };

  return {
    content: JSON.stringify(zedTheme, null, 2),
    filename: `${theme.name.toLowerCase().replace(/\s+/g, "-")}`,
    extension: "json",
  };
}

// Convert VSCode theme to Neovim Lua format
export function convertToNeovim(theme: VSCodeTheme): ExportFormat {
  const luaContent = `-- ${theme.name} colorscheme for Neovim
-- Generated by Theme Editor

local M = {}

-- Color palette
M.palette = {
  bg = "${theme.colors["editor.background"] || "#1e1e1e"}",
  fg = "${theme.colors["editor.foreground"] || "#d4d4d4"}",
  selection = "${theme.colors["editor.selectionBackground"] || "#264f78"}",
  comment = "${theme.tokenColors.find((t) => t.scope.includes("comment"))?.settings.foreground || "#6a9955"}",
  keyword = "${theme.tokenColors.find((t) => t.scope.includes("keyword"))?.settings.foreground || "#569cd6"}",
  string = "${theme.tokenColors.find((t) => t.scope.includes("string"))?.settings.foreground || "#ce9178"}",
  func = "${theme.tokenColors.find((t) => t.scope.includes("entity.name.function"))?.settings.foreground || "#dcdcaa"}",
  variable = "${theme.tokenColors.find((t) => t.scope.includes("variable"))?.settings.foreground || "#9cdcfe"}",
  number = "${theme.tokenColors.find((t) => t.scope.includes("constant.numeric"))?.settings.foreground || "#b5cea8"}",
  type = "${theme.tokenColors.find((t) => t.scope.includes("entity.name.type"))?.settings.foreground || "#4ec9b0"}",
  operator = "${theme.tokenColors.find((t) => t.scope.includes("keyword.operator"))?.settings.foreground || "#d4d4d4"}",
}

-- Apply colorscheme
function M.setup()
  vim.cmd('hi clear')
  if vim.fn.exists('syntax_on') then
    vim.cmd('syntax reset')
  end
  
  vim.o.termguicolors = true
  vim.g.colors_name = "${theme.name.toLowerCase().replace(/\s+/g, "_")}"
  
  local p = M.palette
  
  -- Editor highlights
  vim.api.nvim_set_hl(0, "Normal", { fg = p.fg, bg = p.bg })
  vim.api.nvim_set_hl(0, "Visual", { bg = p.selection })
  vim.api.nvim_set_hl(0, "Comment", { fg = p.comment, italic = true })
  
  -- Syntax highlights
  vim.api.nvim_set_hl(0, "Keyword", { fg = p.keyword })
  vim.api.nvim_set_hl(0, "String", { fg = p.string })
  vim.api.nvim_set_hl(0, "Function", { fg = p.func })
  vim.api.nvim_set_hl(0, "Variable", { fg = p.variable })
  vim.api.nvim_set_hl(0, "Number", { fg = p.number })
  vim.api.nvim_set_hl(0, "Type", { fg = p.type })
  vim.api.nvim_set_hl(0, "Operator", { fg = p.operator })
  
  -- Treesitter highlights
  vim.api.nvim_set_hl(0, "@keyword", { link = "Keyword" })
  vim.api.nvim_set_hl(0, "@string", { link = "String" })
  vim.api.nvim_set_hl(0, "@function", { link = "Function" })
  vim.api.nvim_set_hl(0, "@variable", { link = "Variable" })
  vim.api.nvim_set_hl(0, "@number", { link = "Number" })
  vim.api.nvim_set_hl(0, "@type", { link = "Type" })
  vim.api.nvim_set_hl(0, "@operator", { link = "Operator" })
  vim.api.nvim_set_hl(0, "@comment", { link = "Comment" })
end

return M
`;

  return {
    content: luaContent,
    filename: `${theme.name.toLowerCase().replace(/\s+/g, "_")}`,
    extension: "lua",
  };
}

// Convert VSCode theme to Helix TOML format
export function convertToHelix(theme: VSCodeTheme): ExportFormat {
  const tomlContent = `# ${theme.name} theme for Helix
# Generated by Theme Editor

"ui.background" = "bg"
"ui.text" = "fg"
"ui.selection" = "selection"
"ui.cursor" = "cursor"
"ui.linenr" = "line_number"
"ui.linenr.selected" = "line_number_active"

"comment" = { fg = "comment", modifiers = ["italic"] }
"keyword" = "keyword"
"string" = "string"
"function" = "function"
"variable" = "variable"
"constant.numeric" = "number"
"type" = "type"
"operator" = "operator"

[palette]
bg = "${theme.colors["editor.background"] || "#1e1e1e"}"
fg = "${theme.colors["editor.foreground"] || "#d4d4d4"}"
selection = "${theme.colors["editor.selectionBackground"] || "#264f78"}"
cursor = "${theme.colors["editorCursor.foreground"] || "#aeafad"}"
line_number = "${theme.colors["editorLineNumber.foreground"] || "#858585"}"
line_number_active = "${theme.colors["editorLineNumber.activeForeground"] || "#c6c6c6"}"
comment = "${theme.tokenColors.find((t) => t.scope.includes("comment"))?.settings.foreground || "#6a9955"}"
keyword = "${theme.tokenColors.find((t) => t.scope.includes("keyword"))?.settings.foreground || "#569cd6"}"
string = "${theme.tokenColors.find((t) => t.scope.includes("string"))?.settings.foreground || "#ce9178"}"
function = "${theme.tokenColors.find((t) => t.scope.includes("entity.name.function"))?.settings.foreground || "#dcdcaa"}"
variable = "${theme.tokenColors.find((t) => t.scope.includes("variable"))?.settings.foreground || "#9cdcfe"}"
number = "${theme.tokenColors.find((t) => t.scope.includes("constant.numeric"))?.settings.foreground || "#b5cea8"}"
type = "${theme.tokenColors.find((t) => t.scope.includes("entity.name.type"))?.settings.foreground || "#4ec9b0"}"
operator = "${theme.tokenColors.find((t) => t.scope.includes("keyword.operator"))?.settings.foreground || "#d4d4d4"}"
`;

  return {
    content: tomlContent,
    filename: `${theme.name.toLowerCase().replace(/\s+/g, "-")}`,
    extension: "toml",
  };
}

// Cursor uses the same format as VSCode
export function convertToCursor(theme: VSCodeTheme): ExportFormat {
  return {
    content: JSON.stringify(theme, null, 2),
    filename: `${theme.name.toLowerCase().replace(/\s+/g, "-")}-theme`,
    extension: "json",
  };
}

// Main converter function
export function convertTheme(
  theme: VSCodeTheme,
  editor: EditorType,
): ExportFormat {
  switch (editor) {
    case "vscode":
      return {
        content: JSON.stringify(theme, null, 2),
        filename: `${theme.name.toLowerCase().replace(/\s+/g, "-")}-theme`,
        extension: "json",
      };
    case "zed":
      return convertToZed(theme);
    case "cursor":
      return convertToCursor(theme);
    case "neovim":
      return convertToNeovim(theme);
    case "helix":
      return convertToHelix(theme);
    default:
      return convertToCursor(theme);
  }
}
